UDPServer:
  LocalIP: "127.0.0.1"
  LocalPort: 9000

TTSService:
  akId: "sdfsdf34rerf"
  akSecret: "sdfsdf3r2"
  appKey: "sdf34sdfsdf"
  serverURL: "sdfsfsf"
  MaxThread: 10
  MakeTestLog: Flase
  SaveVoiceFilePath: "/sambashare_user"
  ReplacePath: "T:\\"
  voice: "Ruoxi"
  Volumne: 50
  Speed: 0
  PitchRate: 0
  DigitMode: 1
  SurvivalMinute: 3600
  DelFileTime: 23